#ifndef COUCHBASEUTILS_GLOBAL_H
#define COUCHBASEUTILS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COUCHBASEUTILS_LIBRARY)
#  define COUCHBASEUTILSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COUCHBASEUTILSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COUCHBASEUTILS_GLOBAL_H
